### ISSUE TITLE
Unexpected keyword argument 'fn_output_signature'

### ISSUE THREAD

**Issue by rosanarguez** [Tai-Min/ML-Touch-Panel#1]
Hi @Tai-Min,

I'm trying to run your code. I'm interesting on the part of the pointer (I want to test Siamese Networks on OpenVINO and NCS2) but I obtain that error. I'm using tensorflow == 2.0 as you commented but in that versions seems not be the parameter 'fn_ouptut_signature' on the tf.map_fn function (that there is on[ tensorflow == 2.4.1](https://www.tensorflow.org/api_docs/python/tf/map_fn)).

Have you had this problem when you run it? If no, any ideas?

Thanks!

**Comment by Tai-Min** [comment]
Hi, sorry for the late response.

By Tensorflow 2.0 in the article I wanted to distinguish between Tensorflow 1 and Tensorflow 2. I don't remember the exact version I was using but it was version that supported  'fn_output_signature' so I guess that it was  tensorflow >= 2.4.1. If you want to use this model with Tensorflow 2.0 I think you should play with dtype instead of 'fn_output_signature'.
